Repository locaccm/documentManagement, pull requests merged in 2025-05, with the labels that each got.

#12 fix: [AIC-73] - Add epic branch
  .github/workflows/build.yml
Labels: bug

#18 epic: [AIC-25] - Document management
  .env.example
  .gitignore
  README.md
  assets/images/logo.png
  eslint.config.mjs
  jest.config.mjs
  package-lock.json
  package.json
  sonar-project.properties
  src/api_documentation/swagger.ts
  src/interfaces/rentReceiptInterface.ts
  src/middleware/auth.ts
  src/routes/deleteDocument.ts
  src/routes/getDocument.ts
  src/routes/postRentReceipt.ts
  src/server.ts
  src/services/rentReceiptService.ts
  src/templates/pdfTemplate.ts
  src/tests/middleware/auth_test.ts
  src/tests/routes/deleteDocument_test.ts
  src/tests/routes/getDocument_test.ts
  src/tests/routes/postRentReceipt_test.ts
  src/tests/services/rentReceiptService_test.ts
  src/tests/templates/pdfTemplate.ts
  tsconfig.json
Labels: EPIC

#20 feat: [AIC-121] - Add prisma folder
  .gitmodules
Labels: enhancement

#22 fix: [AIC-130] - Fix package.json to delete migrate
  .gitignore
  package.json
Labels: enhancement
